package com.dvr.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Vehicle Entity - Replaces MongoDB Vehicle model
 * 
 * Represents a vehicle in the DVR system.
 * Each vehicle can have:
 * - One assigned driver
 * - Multiple trips
 * - Multiple history entries
 */
@Entity
@Table(name = "vehicles")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Vehicle {
    
    /**
     * Primary key - auto-generated by MySQL
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * Vehicle registration number (e.g., "MH-01-AB-1234")
     * Must be unique
     */
    @Column(nullable = false, unique = true, length = 50)
    private String number;
    
    /**
     * Vehicle model/name (e.g., "Truck", "Bus")
     */
    @Column(length = 100)
    private String model;
    
    /**
     * Current location (text, not GPS coordinates)
     */
    @Column(name = "current_location", length = 200)
    private String currentLocation;
    
    /**
     * Destination location
     */
    @Column(length = 200)
    private String destination;
    
    /**
     * Vehicle status: idle, loading, in-transit
     * Using ENUM type for type safety
     */
    @Column(length = 50)
    @Enumerated(EnumType.STRING)
    private VehicleStatus status = VehicleStatus.IDLE;
    
    /**
     * Many-to-One relationship: Many vehicles can be assigned to one driver
     * @JoinColumn: Specifies the foreign key column name
     * fetch = FetchType.EAGER: Load the driver immediately when loading a vehicle
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "driver_id")
    private Driver driver;
    
    /**
     * One-to-Many relationship: A vehicle has many history entries
     */
    @OneToMany(mappedBy = "vehicle", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<VehicleHistory> history;
    
    /**
     * One-to-Many relationship: A vehicle has many trips
     */
    @OneToMany(mappedBy = "vehicle", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<Trip> trips;
    
    /**
     * Creation timestamp
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
    
    /**
     * Last update timestamp
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
    
    /**
     * Called before saving a new record
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }
    
    /**
     * Called before updating a record
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
